# This is a config for E2B sandbox template.
# You can use template ID (oqhhwzqzd2fjbgsik9lo) or template name (v0-clone) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("v0-clone") # Sync sandbox
# sandbox = await AsyncSandbox.create("v0-clone") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('v0-clone')

team_id = "73d56540-eb65-4d71-90c7-568e60924e7f"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "v0-clone"
template_id = "oqhhwzqzd2fjbgsik9lo"
